### PR TITLE
Update plugin.xml

### PR DESCRIPTION
**Pull request by mallowigi**
Apparently I need to remove the extension. Also hard to test without a build process...

### CODE REVIEW

**Comment by mturlo** [comment]
Submitted as version 1.3.1.

**Comment by mallowigi** [comment]
Thanks. That's a shame I have to wait three days :'(

**Comment by mturlo** [comment]
I think it was closer to two days the last time, but yeah - with a human-based review cycle there's only so much you can do :P

**Comment by mturlo** [comment]
...aaand now it's live already :D

**Comment by mallowigi** [comment]
Great! Now it works! But you need to support more languages (for the color scheme), I'm currently in Ruby and I'm using Darcula's colors.

**Comment by mturlo** [comment]
Well I've put this theme/scheme together based on the languages I'm using personally, so support for some others may be pretty terrible. Can you create an issue for that?

**Pull request merged**
